context:
  name: docling-parse
  version: 2.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_parse-${{ version }}.tar.gz
  sha256: 18823b491b060972df7c2623184896005435b1ec8a9fb5e386427207e2dda0bd
  patches:
    - fix-utfcpp.patch

build:
  number: 0
  skip: win
  script:
    content: python -m pip install . -vv --no-deps --no-build-isolation
    env:
      USE_SYSTEM_DEPS: "on"
  python:
    entry_points:
      - docling-parse = docling_parse.run:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}

    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - ${{ "make" if unix else "ninja" }}
    - pkg-config
  host:
    - python
    - poetry-core
    - pybind11 >=2.13.1
    - pip
    - cxxopts
    - loguru-cpp
    - nlohmann_json
    - utfcpp
    - libjpeg-turbo
    - qpdf
    - zlib
  run:
    - python
    - tabulate >=0.9.0
    - ${{ "pywin32 >=305" if win }}

tests:
  - python:
      imports:
        - docling_parse
      pip_check: true
  - script:
      - docling-parse --help

about:
  summary: Simple package to extract text with coordinates from programmatic PDFs
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - docling_parse/pdf_resources_v2/cmap-resources/LICENSE.md
    - docling_parse/pdf_resources/cmap-resources/LICENSE.md
  homepage: https://github.com/DS4SD/docling-parse

extra:
  recipe-maintainers:
    - hadim
